before_script:
  - "ruby --version"
  - "bundle exec rake test_app"
script: "bundle exec rake"
notifications:
  irc:
    channels:
      - "irc.freenode.org#spree"
    use_notice: true
    skip_join: true

rvm:
  - 2.1.0
  - 2.2.1
